version: '3.8'

services:
  browser-pod:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - BROWSER_HEADLESS=true
      - MAX_CONCURRENT_TASKS=5
      - TASK_TIMEOUT=3600
    volumes:
      - ./storage:/app/storage
      - /dev/shm:/dev/shm  # Shared memory for browser
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - browser-pod
  #   restart: unless-stopped

volumes:
  storage_data:
