[project]
name = "browser-pod"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "browser-use>=0.5.4",
    "fastapi[standard]>=0.116.1",
]
